import { defineCommand } from '../define';

export const quick = defineCommand({
  name: 'quick',
  description: 'Cheat sheet of power-user shortcuts and workflows.',
  usage: 'quick',
  examples: ['quick'],
  category: 'utility',
  handler: async () => ({
    stdout: [
      'Power workflows (type quick anytime):',
      '',
      '  Navigation',
      '    go github        smart switch/open/search',
      '    search github    fuzzy search all sources',
      '    !bm react        bang → bookmark search',
      '    qf mail --all    jump to tab in any window',
      '    find youtube     find tab across windows',
      '    domain github    tabs on a domain',
      '    tab next|prev    cycle tabs',
      '',
      '  Page control',
      '    link / link 1    list & open links (click # to run)',
      '    input / input 1  list & focus fields (input 1 "text")',
      '    image / image 1  list & open images',
      '    press enter      submit / key events',
      '    meta             page title & OG tags',
      '    images / image 1 list & open images',
      '    seek login       find-in-page (Ctrl+F)',
      '    read | ai summarize   article → summary',
      '    pick | clip      copy selection',
      '    zoom / volume    page zoom & media',
      '    mute / audible   tab mute / noisy tabs',
      '',
      '  Tab management',
      '    close            close current tab',
      '    tab / tab 2      list tabs / switch to #2',
      '    window / window 2  list windows / focus W#2',
      '    open             new blank tab',
      '    bookmark         bookmark current page',
      '    bookmark react   search → bookmark 1 opens',
      '    tabs --all       all windows',
      '    pinned           pinned tabs',
      '    title "Notes"    rename tab',
      '    discard          unload current tab',
      '    reload --hard    bypass cache',
      '',
      '  Shell',
      '    here --json      tab metadata',
      '    clip md          markdown link',
      '    clip log         copy session transcript',
      '    export log       save + download transcript',
      '    wait 1000        pause ms',
      '    !!  /  !g query  history / bang search',
      '    watch 5 tabs     repeat command interval',
      '    recent restore 1 reopen closed tab',
      '    overlay half     resize terminal overlay',
      '    log / export log session transcript',
      '    notify "Done"    desktop notification',
      '    perf             page load metrics',
      '    pin / unpin      tab pin shortcuts',
      '',
      '  Privacy & data',
      '    siteinfo              audit cookies/history for site',
      '    siteinfo --compare X  compare two sites',
      '    permissions           site content settings',
      '    forget preset light   named wipe profiles',
      '    forget --dry-run      preview site wipe',
      '    forget -f             wipe current site data',
      '    cat /audit/log.txt    destructive command log',
      '    cookies clear -f      clear site cookies',
      '    storage clear -f      clear page storage',
      '    history today         today\'s browsing',
      '    history delete 3 -f   remove history entry',
      '',
      '  Downloads & sessions',
      '    downloads             list recent files (click # to open)',
      '    ls /downloads         VFS browse downloads',
      '    downloads show 1    reveal in Finder/Explorer',
      '    downloads open 1    launch downloaded file',
      '    extensions            list browser extensions',
      '    session save work     snapshot all windows',
      '    session restore work  reopen saved layout',
      '',
      '  Dev / inspect',
      '    audit            page health snapshot',
      '    tech             detect React/Next/WP…',
      '    reqs --slow      network bottlenecks',
      '    storage / cookies  page storage',
      '    viewport (vp)    scroll & dimensions',
      '    frames           iframe inventory',
      '    jsonld           structured data',
      '    env              shell variables',
      '',
      '  Pipelines',
      '    tabs --all | grep github',
      '    read | head -n 30',
      '    links docs | head -n 5',
      '    audit && tech && reqs --slow',
    ].join('\n'),
    exitCode: 0,
  }),
});