import * as dev from './dev-scripts';
import * as scripts from './page-scripts';

export const PAGE_SCRIPT_NAMES = [
  'seekInPage',
  'scrollPage',
  'setPageVolume',
  'grepPageText',
  'listPageLinks',
  'clickTarget',
  'clickLinkAtIndex',
  'setPageTitle',
  'fillElement',
  'getSelectionText',
  'extractReadableText',
  'listPageInputs',
  'focusInputAtIndex',
  'fillInputAtIndex',
  'clearInputAtIndex',
  'pressKey',
  'getPageMeta',
  'listPageImages',
  'getPageAudit',
  'detectTech',
  'listStorage',
  'getStorageItem',
  'getPageRequests',
  'getViewportInfo',
  'listFrames',
  'listCookies',
  'getJsonLd',
  'clearPageStorage',
] as const;

export type PageScriptName = (typeof PAGE_SCRIPT_NAMES)[number];

export const PAGE_SCRIPT_REGISTRY: Record<PageScriptName, (...args: unknown[]) => unknown> = {
  seekInPage: (...args) => scripts.seekInPage(...(args as [string, boolean])),
  scrollPage: (...args) => scripts.scrollPage(...(args as [string, number])),
  setPageVolume: (...args) => scripts.setPageVolume(...(args as [string, number])),
  grepPageText: (...args) => scripts.grepPageText(...(args as [string, number])),
  listPageLinks: (...args) => scripts.listPageLinks(...(args as [string, number])),
  clickTarget: (...args) => scripts.clickTarget(...(args as [string])),
  clickLinkAtIndex: (...args) => scripts.clickLinkAtIndex(...(args as [number, string])),
  setPageTitle: (...args) => scripts.setPageTitle(...(args as [string])),
  fillElement: (...args) => scripts.fillElement(...(args as [string, string])),
  getSelectionText: () => scripts.getSelectionText(),
  extractReadableText: (...args) => scripts.extractReadableText(...(args as [number])),
  listPageInputs: (...args) => scripts.listPageInputs(...(args as [string, number])),
  focusInputAtIndex: (...args) => scripts.focusInputAtIndex(...(args as [number, string])),
  fillInputAtIndex: (...args) => scripts.fillInputAtIndex(...(args as [number, string, string])),
  clearInputAtIndex: (...args) => scripts.clearInputAtIndex(...(args as [number, string])),
  pressKey: (...args) => scripts.pressKey(...(args as [string])),
  getPageMeta: () => scripts.getPageMeta(),
  listPageImages: (...args) => scripts.listPageImages(...(args as [string, number])),
  getPageAudit: () => dev.getPageAudit(),
  detectTech: () => dev.detectTech(),
  listStorage: (...args) => dev.listStorage(...(args as [string, string, number])),
  getStorageItem: (...args) => dev.getStorageItem(...(args as [string, string])),
  getPageRequests: (...args) => dev.getPageRequests(...(args as [string, number, number])),
  getViewportInfo: () => dev.getViewportInfo(),
  listFrames: (...args) => dev.listFrames(...(args as [number])),
  listCookies: () => dev.listCookies(),
  getJsonLd: (...args) => dev.getJsonLd(...(args as [number])),
  clearPageStorage: () => dev.clearPageStorage(),
};